name: Otomatik Guncelleme Sistemi

on:
  push:
    branches:
      - main


jobs:
  sistemi-guncelle:
    runs-on: self-hosted

    steps: 
      - name: 1. Yeni Kodlari GitHub'dan Cek
        uses: actions/checkout@v3

      - name: 2. Kutuphaneleri Guncelle
        run: npm install

      - name: 3. Basari Mesaji Yazdir
        run: echo "🚀 TEBRIKLER! Yeni kodlar basarıyla MacBook'a cekildi ve sistem guncellendi!"